name: Flat Earth Psy
favicon: null
layout_spectrum: 0.88677
typography_spectrum: 0.7945780206937343
title: Exposing the Flat Earth PsyOp
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#133b52'
    - '#a4a4a4'
    - '#8a8954'
    - '#dcc59d'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
