name: Flat Earth Psy
favicon: null
layout_spectrum: 0.88677
typography_spectrum: 0.7945780206937343
title: Exposing the Flat Earth PsyOp
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f737c'
    - '#b2b7ba'
    - '#535762'
    - '#131a2c'
    - '#323a47'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
